import {
  addTimerLap,
  cancelReminder,
  createSoftwareReminderRule,
  createReminder,
  disableSoftwareReminderRule,
  dismissToolAlert,
  getToolAlerts,
  getToolsSnapshot,
  onToolAlert,
  onToolsRuntimeChanged,
  pausePomodoro,
  pauseTimer,
  resetPomodoro,
  resetTimer,
  resumePomodoro,
  resumeTimer,
  skipPomodoroPhase,
  startPomodoro,
  startTimer,
} from "../../../platform/runtime/toolsRuntimeGateway.ts";

export const ToolsRuntimeService = {
  addTimerLap,
  cancelReminder,
  createSoftwareReminderRule,
  createReminder,
  disableSoftwareReminderRule,
  dismissToolAlert,
  getToolAlerts,
  getToolsSnapshot,
  onToolAlert,
  onToolsRuntimeChanged,
  pausePomodoro,
  pauseTimer,
  resetPomodoro,
  resetTimer,
  resumePomodoro,
  resumeTimer,
  skipPomodoroPhase,
  startPomodoro,
  startTimer,
};
